import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const tokensRoot = path.join(projectRoot, "src", "tokens");
const outputFile = path.join(projectRoot, "src", "styles", "tokens.generated.css");

const orderedGroups = ["core", "semantic", "components"];
const requiredFiles = {
  core: ["colors.json", "typography.json", "spacing.json", "layout.json", "motion.json", "effects.json"],
  semantic: ["foundations.json"],
  components: ["button.json", "nav.json", "card.json", "form.json"]
};

const isPlainObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);

const toKebab = (value) =>
  String(value)
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();

const shouldSkipKey = (key) => key.startsWith("$") || key.startsWith("_");

function flattenTokens(object, pathParts = [], output = []) {
  const entries = Object.entries(object);
  for (const [key, value] of entries) {
    if (shouldSkipKey(key)) continue;
    const nextPath = [...pathParts, toKebab(key)];
    if (isPlainObject(value)) {
      flattenTokens(value, nextPath, output);
      continue;
    }
    if (typeof value !== "string" && typeof value !== "number") {
      throw new Error(`Token ${nextPath.join(".")} must be a string or number.`);
    }
    output.push({ name: `--${nextPath.join("-")}`, value: String(value) });
  }
  return output;
}

async function readJson(filePath) {
  const content = await fs.readFile(filePath, "utf8");
  return JSON.parse(content);
}

async function validateRequiredFiles() {
  for (const [group, files] of Object.entries(requiredFiles)) {
    for (const file of files) {
      const fullPath = path.join(tokensRoot, group, file);
      try {
        await fs.access(fullPath);
      } catch {
        throw new Error(`Missing required token source: ${path.relative(projectRoot, fullPath)}`);
      }
    }
  }
}

async function collectGroupTokens(groupName) {
  const groupDir = path.join(tokensRoot, groupName);
  const files = (await fs.readdir(groupDir)).filter((file) => file.endsWith(".json")).sort();
  const groups = [];

  for (const fileName of files) {
    const filePath = path.join(groupDir, fileName);
    const json = await readJson(filePath);
    const flattened = flattenTokens(json).sort((a, b) => a.name.localeCompare(b.name));
    groups.push({ fileName, tokens: flattened });
  }

  return groups;
}

function formatCss(groupedTokens) {
  const lines = [
    "/* This file is auto-generated by scripts/build-tokens.mjs */",
    "/* Do not edit directly. Edit files in src/tokens instead. */",
    "",
    "@theme {"
  ];

  for (const group of groupedTokens) {
    lines.push(`  /* ${group.groupName.toUpperCase()} TOKENS */`);
    for (const file of group.files) {
      lines.push(`  /* ${file.fileName} */`);
      for (const token of file.tokens) {
        lines.push(`  ${token.name}: ${token.value};`);
      }
      lines.push("");
    }
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

async function main() {
  await validateRequiredFiles();

  const groupedTokens = [];
  for (const groupName of orderedGroups) {
    groupedTokens.push({
      groupName,
      files: await collectGroupTokens(groupName)
    });
  }

  const css = formatCss(groupedTokens);
  await fs.writeFile(outputFile, css, "utf8");
  process.stdout.write(`Generated ${path.relative(projectRoot, outputFile)}\n`);
}

main().catch((error) => {
  process.stderr.write(`${error.message}\n`);
  process.exit(1);
});
